# bash_aliases

alias ls='ls -G'
alias ..='cd ..'
alias cd..='cd ..'
alias clr='clear'
alias cp='cp -i'
alias d='ls'
alias df='df hT'
alias grep='grep --color=auto -d skip'
alias lla='ls -Ahl'
alias la='ls -Ah'
alias lmeta='ls -Ahl@e'
alias ll='ls -hl'
alias llk='ls -lShr'
alias llc='ls -lcr'
alias lc='ls -cr'
alias llu='ls -lur'
alias llR='ls -lR'
alias llt='ls -ltr'
alias llm='ls -lag * | more'
alias loc='set -f; _loc'
alias more='less'
alias mv='mv -i'
alias p='cd -'
alias rgrep='grep -r'
alias rm='rm -i'
alias s='cd ..'
alias top='top -i'
alias vi='vim'
